name: My Open Catalogi Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:              
      - name: Create or Update opencatalogi.yaml
        uses: OpenCatalogi/publiccode-action@1.1.0
        with:
          opencatalogi: true
      - name: Create an Open Catalogi page
        uses: OpenCatalogi/opencatalogi-action@1.0.0-SNAPSHOT.17.53cda65
